version: '2'
services:
  sentrifugo-app:
    build: .
    links:
      - sentrifugo-db:sentrifugo-db
    depends_on:
      - sentrifugo-db
    ports:
      - "8080:80"
  sentrifugo-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
